### ISSUE TITLE
Two libraries, same content

### ISSUE THREAD

**Issue by Bradan** [eyce9000/strontium#2]
I tried using this library, but when trying to combine the Paleo classes and SketchController I always have to convert between the Stroke types. Once in package edu.tamu.core.sketch and once in srl.core.sketch. It should be easier to combine them.

**Comment by eyce9000** [comment]
What are you trying to do with the SketchController?

If you are using Sr Core and Sr Recognition, you should not need to ever use the edu.tamu.core.sketch package.

Please note that with the latest update you can use maven with the Core and Recognition libraries.

**Comment by Bradan** [comment]
Sorry, I've already found out that I should use BasicController instead when using the Paleo library. I initially thought Paleo uses the Core library, but it has duplicated all classes from the Core library into the Paleo library. So you can't use Core with Recognition, you can either use Recognition or Core. BasicController from Paleo doesn't use Core Sketches, it uses Paleo Sketches, which simply seem to be a copy of the core package into a different package. This design is very irritating. The term "Core" usually implies this library is always necessary, but "Paleo" seems to include the "Core" partially again with some renaming (BasicController instead of SketchController, JSketchCanvas instead of SketchCanvas, ...). I initially thought the "Core" would provide all data management classes for the shapes and so on for every other library.

**Comment by eyce9000** [comment]
Which Paleo library are you using? There is a copy of the legacy Paleo library in the Sr Legacy eclipse project, but for new development I would suggest avoiding that.

All necessary sketch container objects are in Sr Core (sr-core) and all recognition classes are in Sr Recognition (sr-rec). If possible, simply use those two jars and you should have everything you need for creating sketches and for performing recognition on them.

**Comment by Bradan** [comment]
Ah, sorry, I thought I would have to use the paleo.jar for sketch recognition.
