### ISSUE TITLE
Beautified information not filled

### ISSUE THREAD

**Issue by Bradan** [eyce9000/strontium#3]
I tried to use the getBeautifiedShape(), but it is not filled with information after recognition. How can I get a beautified version of a shape? Where can I ask questions? This issue tracker seems to be a bad place for it. Is there some kind of documentation for this library?

**Comment by eyce9000** [comment]
getBeautiffiedShape() is generally used after a sketch object has been passed through the recognizer. Before then, if you want a drawable shape, use toSVGShape()

This provides you with an SVGShape object that can be rendered using either 

org.openawt.draw.android.ShapePainter.draw()

or

org.openawt.draw.awt.ShapePainter.draw()


There is not really any good documentation for this library at the moment, but it is certainly valid to open an issue for it!

**Comment by Bradan** [comment]
Thanks for your answer, but even though I used a recognizer first, the beautified shape is never available on the best shape:

```java
    canvas.addObserver(new ISketchObserver() {
            @Override
            public void penUpEvent(Sketch sketch) {
                Stroke stroke = sketch.getLastStroke();
                PaleoSketchRecognizer recognizer = new PaleoSketchRecognizer(PaleoConfig.allOn());
                recognizer.setStroke(stroke);
                IRecognitionResult result = recognizer.recognize();
                Shape bestShape = result.getBestShape();
                if(bestShape != null)
                    System.out.println(bestShape.getBeautifiedShape()); // always prints "null"
                ...
```

**Comment by eyce9000** [comment]
Instead of using that function, use the toSVGShape() method on the Shape returned by the recognizer. Essentially the Shape is already beautified since it is the ideal form of the recognized shape, so all we need to do now is get the renderable version of the shape.

I am going to work on removing the IBeautifiable interface as it is essentially meaningless at this point.

Here is the preferred way to do this:

```java
PaleoSketchRecognizer recognizer = new PaleoSketchRecognizer(PaleoConfig.allOn());
recognizer.setStroke(stroke);
IRecognitionResult result = recognizer.recognize();
Shape bestShape = result.getBestShape();
System.out.println(bestShape.getInterpretation().label);
SVGShape drawShape = bestShape.toSVGShape();
ShapePainter.draw(canvas,drawShape,drawStyle);
```

**Comment by Bradan** [comment]
Nice, now it works, thanks.

**Comment by eyce9000** [comment]
Looks like the beautified shapes need to stay in cases where you explicitly need to set the beautified shape. For drawing, always use toSVGShape(), this will get you either the beautified shape if present, or an SVG representation of the shape if not.
